### ISSUE TITLE
RFE: Clarification of 2E Etiquette Concentrations

### ISSUE THREAD

**Issue by ramrodofavalon** [criticalfault/Shadowrun-Character-Generator#2]
This may be user error but I believe in 2E all Etiquette is concentrated and thus, does not get the bonus point, nor is there a base Etiquette skill

<img width="549" alt="image" src="https://github.com/criticalfault/Shadowrun-Character-Generator/assets/16293857/af5e1577-e530-4361-a459-06d53323b814">

**Comment by criticalfault** [comment]
This should be resolved as of #47. Hopefully that fixes it up for you!
