### ISSUE TITLE
Skill Issues

### ISSUE THREAD

**Issue by darkbushido** [criticalfault/Shadowrun-Character-Generator#77]
On a fresh character sheet you cannot add the following skills:

- Magical skills
  - Aura Reading
- Physical Skills
  - Athletics
- Social skills
  - Acting
- Survival
  - Riding
- Technical skills
  - Biotech
- Vehicle
  - Bike
- Build/Repair
  - Armor B/R
- Otaku
  - Access Channel

If you can add the skill they show up as assault rifles.
If you remove the added assault rifles you cannot add Combat - Assault Rifles

It looks like the first skill of each category is a problem, sometimes you can add a skill, edit it and add one of the listed skills 
 
Biotech does not show its specializations.

**Comment by criticalfault** [comment]
Alright, i made a change (And i'll have another one soon) that -should- have fixed when you change the category. It still needs some fixes on defaulting the "none" on the ORIGINAL load, but at least when you change it now, it should fix it. Let me know if this fixed it?

**Comment by darkbushido** [comment]
Looks like its working, Thank you

**Comment by criticalfault** [comment]
Awesome! Great catch! Thank you for the ticket! If you find anything else just hit me up. I'll try to get it taken care of!
